Start with better test scripts.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,18 +1,17 @@
-#!/bin/sh
+#!/bin/bash
 
-indent() {
-  sed -u 's/^/       /'
+# fail fast
+set -o errexit
+set -o pipefail
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
 }
 
-echo "-----> Found a hello.txt"
-
-# if hello.txt has contents, display them (indented to align)
-# otherwise error
-
-if [ ! -s $1/hello.txt ]; then
-  echo "hello.txt was empty"
-  exit 1
-else
-  echo "hello.txt is not empty, here are the contents" | indent
-  cat $1/hello.txt
-fi | indent
+cd $1
+echo "-----> Running bin/test"
+bin/test | indent
